version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    container_name: app
    build: .
    env_file:
      - .env
    environment:
      - IS_DOCKER_RUN=true
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped
